# Generated by Django 4.2.16 on 2024-09-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('pescatarian', 'Pescatarian'), ('gluten-free', 'Gluten-free'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('other', 'Other')], max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='dish',
            name='dietary_preference',
        ),
        migrations.AddField(
            model_name='dish',
            name='dietary_preference',
            field=models.ManyToManyField(to='dishes.dietarypreference'),
        ),
    ]
