# Generated by Django 4.2.16 on 2024-09-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_dietarypreference_remove_dish_dietary_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietarypreference',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.RemoveField(
            model_name='dish',
            name='dietary_preference',
        ),
        migrations.AddField(
            model_name='dish',
            name='dietary_preference',
            field=models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('pescatarian', 'Pescatarian'), ('gluten-free', 'Gluten-free'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('other', 'Other')], default='vegetarian', max_length=25),
            preserve_default=False,
        ),
    ]
