# Generated by Django 4.2.16 on 2024-09-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_alter_dish_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DietaryPreference',
        ),
    ]
